### PR TITLE
[WIP] rclcpp design

### PR DESCRIPTION
**Pull request by Theosakamg**
_Need to remove my Travis and Readme._

* Packages node, services, topics...
* New c/JNI message generator:
 * fixed Char converter
 * fixed fixed array type
 * fixed String array type
 * JNI cache
* Documentation (JavaDoc)
* Add Logger ROS (not official)
* Add Parameter stack
* More tests
* Refactor JNI loading

### CODE REVIEW

**Comment by esteve** [comment]
@Theosakamg wow, thank you so much, this is awesome! But could you split these changes into separate features? The diff is too huge to review, I don't even know where to start :-)

A consequence of not having clearly separate pull requests is that many commits may not be needed. For example this:

https://github.com/Theosakamg/ros2_java/blob/bb3581bfb3fc720565dbfaf7c04cb5ab047482e8/rcljava/src/main/java/org/ros2/rcljava/Log.java

Since `ros2_java` now uses SLF4J which already abstracts the logging library (log4j, `java.util.logging`, Android, etc.), adding this Log class is not necessary.

Usually, when submitting pull requests, it's best to create self contained branches, so that the author of the changes can discuss with the maintainer. It also helps to keep the commit history cleaner, for example, there are many "Merge branch 'master' of https://github.com/esteve/ros2_java", which makes it harder to understand the changes.

I can help you submit cleaner pull requests, your contributions are really valuable. We can have a look at it together and create separate branches, where would you like to start?

**Comment by esteve** [comment]
@Theosakamg I'd love to merge your contributions, but unfortunately I can't merge this pull request as is. It's important that you split this into separate pull requests, here's a suggestion for how we could get there:

- rename your master branch to something else (e.g. master-Theosakamg in your repository) and clone (https://github.com/esteve/ros2_java/tree/master)
- identify one improvement you think could be merged easily into https://github.com/esteve/ros2_java/tree/master (for example, https://github.com/Theosakamg/ros2_java/blob/ec402f583e3e054905cc4778f8d26cfdb5379dd9/rosidl_generator_java/resource/msg_support.entry_point.cpp.template#L355-L363 in https://github.com/esteve/ros2_java/pull/8/commits/ec402f583e3e054905cc4778f8d26cfdb5379dd9)
- create a branch with just that one change and submit a pull request for it
- I'll accept the pull request and merge it.

I haven't heard from you since you created this pull request, but you have continued to push changes, so I'm really happy that you're still interested in ros2_java :relaxed:

**Comment by esteve** [comment]
@Theosakamg ping. It's been 20 days since you submitted this pull request, but haven't heard from you and I don't know whether you plan to act upon the feedback I gave you. What should I do with this pull request? Should I close it or wait?

**Comment by Theosakamg** [comment]
@esteve sorry for the delay. I rename to WIP. more info => https://github.com/ros2java/design/issues/1#issuecomment-261808345

**Pull request closed without merging**
