### PR TITLE
Fix class_loader & console_bridge_vendor errors

### LINKED ISSUE #49: Dependency missing in `class_loader`, needs `console_bridge_vendor`
```log
Command line warning D9002: ignoring unknown option '-fvisibility=hidden'

error C2065: '__deprecated__': undeclared identifier
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
error C2448: '__attribute__': function-style initializer appears to be a function definition
```

[CMakeError.log](https://github.com/esteve/ros2_java/files/2220665/CMakeError.log)

### PR DESCRIPTION
**Pull request by calvertdw**
Fixes #49 and #51.

### CODE REVIEW

**Comment by esteve** [comment]
In order to mimic the master ROS2 repo (https://github.com/ros2/ros2/blob/master/ros2.repos) as much as possible, I'd keep `class_loader` as is, but switch to `console_bridge_vendor`: https://github.com/ros2/ros2/blob/master/ros2.repos#L78-L81

**Comment by calvertdw** [comment]
I tried that and it didn't work. I forgot why though. I am more focused on getting a build that uses bouncy, because of issues like this. I want to actually use ros2_java more than maintain it.

**Comment by calvertdw** [comment]
Sorry that came off as sour. I'm not! Let me try to build with console_bridge_vendor again.

**Comment by esteve** [comment]
No worries. I'm actually fine with merging this if it gets the job done, though I wonder why `console_bridge_vendor` fails and I would like to fix it so that it works with the next release after bouncy.

**Comment by calvertdw** [comment]
I'm pretty sure there was no error. It was actually something else. I will make another PR, but also fix this one.

**Comment by calvertdw** [comment]
Okay fixed!

**Comment by esteve** [comment]
Thanks!

**Pull request merged**
