### PR TITLE
update README.md for Android build on OSX

### PR DESCRIPTION
**Pull request by qiao-tw**
As mentioned in [#38](https://github.com/esteve/ros2_java/issues/38#issuecomment-386868343). 
This change has been verified under OSX 10.13.4 and Ubuntu 16.04.

### CODE REVIEW

**Comment by esteve** [comment]
@qiao-tw wow, this is awesome, thanks! I was thinking that perhaps it'd be easier for users to have the instructions without any variables at all, like https://github.com/ros2/ros2/wiki/OSX-Development-Setup#build-the-ros-2-code However, I think it'd be really useful to put this in a script, what do you think?

**Comment by qiao-tw** [comment]
@esteve Sure, I agree, but where should this script locate? The 'ci-scripts' ? I'm afraid of breaking the CI though...

**Comment by calvertdw** [comment]
I have jdk8 installed as well.

**Comment by esteve** [comment]
Sorry it's taken so long, I somehow thought it was already merged. Thanks for the patch and the patience!

**Comment by qiao-tw** [comment]
No problem! I'm glad to contribute!

**Pull request merged**
